_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 16
hidden_dim:
    value: 64
input_dim:
    value: 21
learning_rate:
    value: 1.7038845095572865e-05
num_epochs:
    value: 50
optimizer:
    value: adam
scheduler_factor:
    value: 0.5
scheduler_patience:
    value: 4
seed:
    value: 9218
train_split:
    value: 0.766799289204586
valid_split:
    value: 0.1320372594396131
