_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 32
hidden_dim:
    value: 512
input_dim:
    value: 21
learning_rate:
    value: 0.0007410409318065825
num_epochs:
    value: 70
optimizer:
    value: adam
scheduler_factor:
    value: 0.7
scheduler_patience:
    value: 2
seed:
    value: 5490
train_split:
    value: 0.7487558355302463
valid_split:
    value: 0.06237602979481254
