_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 64
hidden_dim:
    value: 256
input_dim:
    value: 21
learning_rate:
    value: 0.00038352186299046035
num_epochs:
    value: 30
optimizer:
    value: adam
scheduler_factor:
    value: 0.6
scheduler_patience:
    value: 2
seed:
    value: 426
train_split:
    value: 0.7645906362675483
valid_split:
    value: 0.13540936373245172
